---
version: '3.7'
services:
  ## PostgreSQL Docker Compose Config
  postgres-currency:
    container_name: postgres-currency
    image: postgres
    environment:
      POSTGRES_DB: currency
      POSTGRES_USER: rashad
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-currency:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  currency-service:
    container_name: currency-service
    image: resadnv/azn-mezenne:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres-currency
    restart: on-failure
